# Generated by Django 5.2 on 2025-05-02 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetailmodel',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='offers_app.offermodel'),
        ),
    ]
