# Generated by Django 5.2 on 2025-05-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_rename_offermodel_offer_offerdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
