# Generated by Django 5.2 on 2025-05-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_profile_uploaded_at_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business')], max_length=50),
        ),
    ]
